site_name: Cantonese

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Swithch to Dark Mode
    # Dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Swithch to Dark Mode

nav:
  - Peppa Pig: peppa_pig/home.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: underbrace
          class: underbrace
          format: !!python/name:builtins.str

plugins:
  - search
extra_css:
  - css/extra.css

extra_javascript:
  - javascripts/extra.js
  - javascripts/math.js
  - javascripts/underbrace.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/nicolasshu/cantonese/
repo_name: nicolasshu/cantonese
